apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: api-ingress
  namespace: api
spec:
  template:
    spec:
      backend:
        serviceName: api-mcs
        servicePort: 8080
