---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: build-robot-rolebinding
# subjects:
# - kind: ServiceAccount
#   name: build-robot
#   namespace: default
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
