apiVersion: v1
kind: List
items:
- apiVersion: cloud.google.com/v1
  kind: BackendConfig
  metadata:
    name: api-demo-v2-backend
  spec:
    securityPolicy:
      name: gce-policy
    # iap:
    #   enabled: false
    #   oauthclientCredentials:
    #     secretName: my-secret
    timeoutSec: 5  # A timeout of seconds
    # connectionDraining:
    #   drainingTimeoutSec: 60 # A connection draining timeout of 60 seconds.
    # sessionAffinity:
    #   affinityType: "CLIENT_IP"
    healthCheck:
      checkIntervalSec: 30
      port: 8080
      requestPath: /v2/manifest.json
      timeoutSec: 25
      healthyThreshold: 3
      unhealthyThreshold: 5
      type: HTTP
