apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dind-demo
  name: dind-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-demo-service-v3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-demo-service-v3
    spec:
      containers:
      - image: gcr.io/kefeng-playground-369510/api-demo:full
        imagePullPolicy: Always
        name: dind-demo
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        ports:
        - containerPort: 8080
          protocol: TCP
        # resources:
          # limits:
            # cpu: "1"
            # memory: 1280Mi
        #   requests:
        #     cpu: "1"
        #     memory: 1280Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: dind-daemon
        image: docker:stable-dind
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        # resources:
          # limits:
            # cpu: "1"
            # memory: 1280Mi
          # requests:
          #   cpu: 20m
          #   memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-graph-store
            mountPath: /var/lib/docker
#      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: build-robot
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: docker-graph-store
          emptyDir: {}
