---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-demo-v3
  name: api-demo-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-demo-service-v3
  type: LoadBalancer
