---
apiVersion: v1
kind: List
items:
- apiVersion: networking.gke.io/v1
  kind: MultiClusterService
  metadata:
    name: api-mcs
    namespace: api
  spec:
    template:
      spec:
        selector:
          app: api-demo-service-v3
        ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080

