apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          automountServiceAccountToken: true
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
