apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-demo
  name: api-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-demo-service
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-demo-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api-demo
                      - api-demo-service
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: gcr.io/kefeng-playground-369510/api-demo:node-v3
        imagePullPolicy: Always
        name: api-demo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
            nvidia.com/gpu: 1
          requests:
            cpu: 300m
            memory: 256Mi
            nvidia.com/gpu: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
    #  dnsPolicy: ClusterFirst
      restartPolicy: Always
      # serviceAccountName: build-robot
      nodeSelector:
        # iam.gke.io/gke-metadata-server-enabled: "true"
        cloud.google.com/gke-nodepool: pool-1
        cloud.google.com/gke-accelerator: nvidia-tesla-p4
      terminationGracePeriodSeconds: 30
      volumes:
        - name: docker-graph-store
          emptyDir: {}
