apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-vault-service
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  # Overrides cluster DEFAULT_VAULT_MOUNT_POINT
  # vaultMountPoint: http://172.18.255.200:8200
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  # Overrides cluster DEFAULT_VAULT_ROLE
  #vaultAddr: http://172.18.255.200:8200
  #vaultToken: s.bdKelT7Z902VfPYxTqwXU73W
  vaultRole: external-app
  data:
    - name: password
      key: secret/external/database/config
      property: password
    - name: username
      key: secret/external/database/config
      property: username
