apiVersion: v1
kind: List
items:
- apiVersion: cloud.google.com/v1
  kind: BackendConfig
  metadata:
    name: api-demo-v3-backend
  spec:
    # iap:
    #   enabled: false
    #   oauthclientCredentials:
    #     secretName: my-secret
    healthCheck:
      checkIntervalSec: 30
      port: 8080
      requestPath: /manifest.json
      timeoutSec: 25
      type: HTTP
    timeoutSec: 25
- apiVersion: cloud.google.com/v1
  kind: BackendConfig
  metadata:
    name: api-demo-v2-backend
  spec:
    # iap:
    #   enabled: false
    #   oauthclientCredentials:
    #     secretName: my-secret
    healthCheck:
      checkIntervalSec: 30
      port: 8080
      requestPath: /manifest.json
      timeoutSec: 25
      type: HTTP
    timeoutSec: 25
